server:
  port: 8080
spring:
  profiles:
    active: local

springdoc:
  paths-to-match:
    - /api/v1/**
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: info,health,loggers
