---
name: Build
on:
  push:
    branches:
      - master
    paths:
      - .github/**
      - docker-compose.yml
      - gateway/**
      - dictionary/**
      - build.gradle
      - gradle.properties
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"
          cache: "gradle"

      - name: Validate
        uses: pre-commit/action@v3.0.0

      - name: Build project
        run: ./gradlew clean build
